config/routes.rb
Rails.application.routes.draw do
  # resources :character_encounters
  # resources :monster_encounters
  resources :char_class, only: [:index, :show]
  resources :char_race, only: [:index, :show]
  resources :alignment, only: [:index, :show]

  get "/pets/search", to: "pets#search", as: "pets_search"
  # resources :pets
  get "/characters/search", to: "characters#search", as: "characters_search"
  resources :characters
  get "/monsters/search", to: "monsters#search", as: "monsters_search"
  resources :monsters
  get "/encounters/search", to: "encounters#search", as: "encounters_search"
  get "/encounters/preview", to: "encounters#preview", as: "encounter_preview"
  get "/encounters/:id/edit/preview", to: "encounters#edit_preview", as: "edit_encounter_preview"
  resources :encounters


  get '/login', to: 'sessions#new', as: 'login'
  post '/sessions', to: 'sessions#create', as: 'sessions'
  post '/logout', to: 'sessions#destroy'

  resources :users, except: :index
  get '/signup', to: 'users#new', as: 'register'

  get '/users/:id/encounters', to: 'users#encounters_index', as: 'my_encounters'
  get '/users/:id/encounters/:encounter_id', to: 'users#encounter_show', as: 'my_encounter'

  get '/users/:id/characters', to: 'users#characters_index', as: 'my_characters'
  get '/users/:id/characters/:character_id', to: 'users#character_show', as: 'my_character'

  get '/users/:id/monsters', to: 'users#monsters_index', as: 'my_monsters'
  get '/users/:id/monsters/:monster_id', to: 'users#monster_show', as: 'my_monster'

  root 'application#home'
  get '/analytics', to: 'application#analytics'

  get "*path", to: 'application#redirect'
end

app/models/monster.rb
class Monster < ApplicationRecord
  has_many :monster_encounters
  has_many :encounters, through: :monster_encounters
  belongs_to :user, optional: true

  # validates :name, :description, :hit_points, :size, :challenge_rating, :strength, :dexterity, :constitution, :intelligence, :wisdom, :charisma, :armor_class, presence: true
  validates :hit_points, inclusion: { in: 1..500, message: "value must be between 1 and 500."}

  def stats
    {strength: strength, dexterity: dexterity, constitution: constitution, intelligence: intelligence, wisdom: wisdom, charisma: charisma}
  end

  def quantity_by_encounter(encounter)
    encounter.monster_encounters.find_by(monster_id: self.id).quantity
  end

  def monster_name_and_cr
    "#{name} || CR #{challenge_rating}"
  end

  MONSTER_SIZES = ["Tiny", "Small", "Medium", "Large", "Huge", "Gargantuan"]

  end

app/controllers/monsters_controller.rb
class MonstersController < ApplicationController
  def index
    @monsters = Monster.all
  end

  def search
    find_monster_by_name
    if @monsters.length > 0
      render :index
    else
      flash[:errors] = "That monster does not exist."
      redirect_to monsters_path
    end
  end

  def new
    @monster = Monster.new
  end

  def create
    @monster = Monster.create(monster_params)

    if @monster.valid? && logged_in?
      @monster.update(user_id: current_user.id)
      redirect_to my_monster_path(current_user.id, @monster)
    elsif @monster.valid?
      redirect_to monster_path(@monster)
    else
      flash[:errors] = @monster.errors.full_messages
      redirect_to new_monster_path
    end

  end

  def show
    find_monster_by_id # Assigns monster to @monster
  end

  def edit
    find_monster_by_id # Assigns monster to @monster

    if !permitted?(@monster.user)
      flash[:notice] = "You are not authorized to edit this item."
      redirect_to @monster
    end
  end

  def update
    find_monster_by_id # Assigns monster to @monster
    @monster.update(monster_params)

    redirect_to monster_path
  end

  def destroy
    find_monster_by_id # Assigns monster to @monster
    if permitted?(@monster.user)
      @monster.delete
      flash[:notice] = "Monster Deleted."
      redirect_to my_monsters_path
    else
      flash[:notice] = "You are not authorized to delete that item."
      redirect_to monsters_path
    end
  end

  private

  def monster_params
    params.require(:monster).permit(:name, :description, :hit_points, :size, :challenge_rating, :strength, :dexterity, :constitution, :intelligence, :wisdom, :charisma, :armor_class, :constitution_save, :wisdom_save, :intelligence_save, :history, :perception)
  end

  def find_monster_by_id
    @monster = Monster.find(params[:id])
  end

  def find_monster_by_name
    @monsters = Monster.where(Monster.arel_table[:name].lower.matches(params[:search_term].downcase))
  end

end

app/helpers/monsters_helper.rb
module MonstersHelper
end

app/views/monsters/_heading.html.erb
<img src="https://orig00.deviantart.net/d0fb/f/2017/294/2/8/dungeons_and_dragons_ampersand_by_darthiraecorpus-dbr99rk.png" width="100 height="100">

app/views/monsters/_monsterform.html.erb
<%= form_for @monster do |f| %>
<div class="monster_background_new">
<br><br><br><br><br><br>
  <%= f.label "Name:", class:"monster_name_label" %>
  <%= f.text_field :name, class: "monster_name_new" %>
    <br><br>
  <%= f.label :size, class:"monster_subtitles_new" %>
    <br>
  <%= f.select(:size, Monster::MONSTER_SIZES, {}, { :class => 'monster_selector_field_new' }) %>
    <br><br>
  <%= f.label :description, class:"monster_subtitles_new" %>
    <br>
  <%= f.text_area :description, class: "monster_textarea_field_new" %>
  <br>
  <img class="monster_dividers_new" src = "/../assets/red-divider.png"><br>
  <%= f.label :challenge_rating, class:"monster_subtitles_new" %>
    <br>
  <%= f.text_field :challenge_rating, class: "monster_number_field" %>
  <br><br>
  <%= f.label :armor_class, class:"monster_subtitles_new" %>
    <br>
  <%= f.number_field :armor_class, class: "monster_number_field" %>
    <br><br>

  <%= f.label :hit_points, class:"monster_subtitles_new" %>
  <br>
  <%= f.number_field :hit_points, class: "monster_number_field" %>
    <br><br>
  <img class="monster_dividers_new" src = "/../assets/red-divider.png">
  <h3 class="monster_show_new">Monster Stats</h3>
  <div class="monster_input_container_new">
  <div class="monster_input_inner_container">
  <%= f.label "STR", class:"monster_form_size_new" %>
    <br>
  <%= f.number_field :strength, class:"monster_strength_new" %>
    <br><br>
  </div>
  <div class="monster_input_inner_container_new">
  <%= f.label "DEX", class:"monster_form_size_new" %>
    <br>
  <%= f.number_field :dexterity, class:"monster_dexterity_new" %>
    <br><br>
  </div>
  <div class="monster_input_inner_container_new">
  <%= f.label "CON", class:"monster_form_size_new" %>
    <br>
  <%= f.number_field :constitution, class:"monster_constitution_new" %>
    <br><br>
  </div>
  <div class="monster_input_inner_container_new">
  <%= f.label "INT", class:"monster_form_size_new" %>
    <br>
  <%= f.number_field :intelligence, class:"monster_intelligence_new" %>
    <br><br>
  </div>
  <div class="monster_input_inner_container_new">
  <%= f.label "WIS", class:"monster_form_size_new" %>
    <br>
  <%= f.number_field :wisdom, class:"monster_wisdom_new" %>
    <br><br>
  </div>
  <div class="monster_input_inner_container_new">
  <%= f.label "CHA", class:"monster_form_size_new" %>
    <br>
  <%= f.number_field :charisma, class:"monster_charisma_new" %>
    <br><br>
  </div>
  </div>
  <img class="monster_dividers_new" src = "/../assets/red-divider.png"><br>
  <h3 class="monster_show_new">Saving Throws</h3>
  <%= f.label :constitution_save, class:"monster_subtitles_new" %>
    <br>
  <%= f.text_field :constitution_save, class: "monster_number_field" %>
    <br><br>

  <%= f.label :intelligence_save, class:"monster_subtitles_new" %>
    <br>
    <%= f.text_field :intelligence_save, class: "monster_number_field" %>
    <br><br>
  <%= f.label :wisdom_save, class:"monster_subtitles_new" %>
    <br>
  <%= f.text_field :wisdom_save, class: "monster_number_field" %>
      <br><br>
  <img class="monster_dividers_new" src = "/../assets/red-divider.png">
  <h3 class="monster_show_new">Skills</h3>
  <%= f.label :history, class:"monster_subtitles_new" %>
    <br>
  <%= f.text_field :history, class: "monster_text_field_new" %>
    <br><br>
  <%= f.label :perception, class:"monster_subtitles_new" %>
    <br>
  <%= f.text_field :perception, class: "monster_text_field_new" %>
  <br><br><br>
    <%= f.submit class: "monster_button_new" %>
    <br><br><br><br><br>
<% end %>
</div>
<br>

<%= button_to "Back to Homepage", root_path, :method => :get, :class => 'back_to_homepage_button' %><br>

app/views/monsters/_search.html.erb
<%= form_tag monsters_search_path, :method => :get do %>
  <%= label_tag(:search_term, "Search Monsters:") %>
  <%= text_field_tag :search_term %>
  <%= submit_tag 'Search Monsters' %>
<% end %>

app/views/monsters/edit.html.erb
<h1>Edit Monster</h1>

<%= render "monsterform" %>

app/views/monsters/index.html.erb
<h1>Current Monsters:</h1>
<%= flash[:notice] if flash[:notice] %>
<br>
<%= render "heading" %>
<br>
<br>
<br>
<%= render "search" %>
<p class="errors"><%= flash[:errors] if flash[:errors] %></p>

<br>

<ul>
<% @monsters.each do |monster| %>
<li class= "monster"><%= link_to monster.name, monster_path(monster) %><%= " (#{monster.description})" %></li>
<% end %>
</ul>
<br><br>

<%= button_to "Create New Monster", monsters_path, {method: :get} %><br>
<%= button_to "<< Back to Homepage", root_path, {method: :get} %>

app/views/monsters/new.html.erb
<%= render "/partials/errors" %>

<h1>Create a Monster</h1>

<%= render "monsterform" %>

app/views/monsters/show.html.erb
<h1><%= @monster.name %></h1>
<span><b>Description:</b> <em><%= @monster.description %></em></span></br>
<span><b>Challenge Rating:</b> <em><%= @monster.challenge_rating %></em></span></br>
<span><b>Armor Class:</b> <em><%= @monster.armor_class %></em></span></br>
<span><b>Hit Points:</b> <em><%= @monster.hit_points %></em></span></br></br>
<ul>
  <li><b>Size:</b> <em><%= @monster.size %></em></li>
  <li><b>Strength:</b> <em><%= @monster.strength %></em></li>
  <li><b>Dexterity:</b> <em><%= @monster.dexterity %></em></li>
  <li><b>Constitution:</b> <em><%= @monster.constitution %></em></li>
  <li><b>Intelligence:</b> <em><%= @monster.intelligence %></em></li>
  <li><b>Wisdom:</b> <em><%= @monster.wisdom %></em></li>
  <li><b>Charisma:</b> <em><%= @monster.charisma %></em></li>
  <li><b>Constituion Saving Throw:</b> <em><%= @monster.constitution_save %></em></li>
  <li><b>Intelligence Saving Throw:</b> <em><%= @monster.intelligence_save %></em></li>
  <li><b>Wisdom Saving Throw:</b> <em><%= @monster.wisdom_save %></em></li>
  <li><b>History:</b> <em><%= @monster.history %></em></li>
  <li><b>Perception:</b> <em><%= @monster.perception %></em></li>
</ul>
<br>
<%= button_to "Edit Monster", edit_monster_path(@monster), {method: :get} %><br>
<%= form_tag @monster, method: "DELETE" do %>
  <%= submit_tag "Delete This Monster" %>
<% end %>
<br>
<%= button_to "<< Return to All Monsters", monsters_path, {method: :get} %><br>