config/routes.rb
Rails.application.routes.draw do
  # resources :character_encounters
  # resources :monster_encounters
  resources :char_class, only: [:index, :show]
  resources :char_race, only: [:index, :show]
  resources :alignment, only: [:index, :show]

  get "/pets/search", to: "pets#search", as: "pets_search"
  # resources :pets
  get "/characters/search", to: "characters#search", as: "characters_search"
  resources :characters
  get "/monsters/search", to: "monsters#search", as: "monsters_search"
  resources :monsters
  get "/encounters/search", to: "encounters#search", as: "encounters_search"
  get "/encounters/preview", to: "encounters#preview", as: "encounter_preview"
  get "/encounters/:id/edit/preview", to: "encounters#edit_preview", as: "edit_encounter_preview"
  resources :encounters


  get '/login', to: 'sessions#new', as: 'login'
  post '/sessions', to: 'sessions#create', as: 'sessions'
  post '/logout', to: 'sessions#destroy'

  resources :users, except: :index
  get '/signup', to: 'users#new', as: 'register'

  get '/users/:id/encounters', to: 'users#encounters_index', as: 'my_encounters'
  get '/users/:id/encounters/:encounter_id', to: 'users#encounter_show', as: 'my_encounter'

  get '/users/:id/characters', to: 'users#characters_index', as: 'my_characters'
  get '/users/:id/characters/:character_id', to: 'users#character_show', as: 'my_character'

  get '/users/:id/monsters', to: 'users#monsters_index', as: 'my_monsters'
  get '/users/:id/monsters/:monster_id', to: 'users#monster_show', as: 'my_monster'

  root 'application#home'
  get '/analytics', to: 'application#analytics'

  get "*path", to: 'application#redirect'
end

app/models/encounter.rb
class Encounter < ApplicationRecord
  has_many :character_encounters
  has_many :characters, through: :character_encounters
  has_many :monster_encounters
  has_many :monsters, through: :monster_encounters
  belongs_to :user, optional: true

  validates :name, :content, :characters, :monsters, presence: true
  validates :name, uniqueness: true

  def monster_quantity(num)
    monster_encounters.each do |m_e|
      m_e.quantity = num
    end
  end

  def encounter_difficulty=(string)
    @encounter_difficulty = string
  end

  def encounter_difficulty
    @encounter_difficulty
  end

end

app/controllers/encounters_controller.rb
class EncountersController < ApplicationController
  def index
    @encounters = Encounter.all
  end

  def search
    find_encounter_by_name
    if @encounters.length > 0
      render :index
    else
      flash[:errors] = "That encounter does not exist."
      redirect_to encounters_path
    end
  end

  def new
    @encounter = Encounter.new
    @characters = Character.all
    monsters_by_cr
  end

  def preview
    @encounter = Encounter.new(encounters_params)
  end

  def create
    @encounter = Encounter.create(encounters_params)

    if @encounter.valid? && logged_in?
      set_monster_quantities(@encounter)
      @encounter.update(user_id: current_user.id)

      calculate_difficulty(@encounter)

      redirect_to my_encounter_path(current_user.id, @encounter)
    elsif @encounter.valid?
      set_monster_quantities(@encounter)

      calculate_difficulty(@encounter)

      redirect_to encounter_path(@encounter)
    else
      flash[:errors] = @encounter.errors.full_messages
      redirect_to new_encounter_path
    end
  end

  def show
    find_encounter_by_id # Sets encounter to @encounter
  end

  def edit
    find_encounter_by_id # Sets encounter to @encounter
    @characters = Character.all
    monsters_by_cr

    if !permitted?(@encounter.user)
      flash[:notice] = "You are not authorized to edit this item."
      redirect_to @encounter
    end
  end

  def edit_preview
    @encounter = Encounter.find(params[:id])
    @encounter.update(encounters_params)
  end

  def update
    find_encounter_by_id # Sets encounter to @encounter

    if @encounter.update(encounters_params)
      set_monster_quantities(@encounter)
      calculate_difficulty(@encounter)
      redirect_to @encounter
    else
      flash[:errors] = @encounter.errors.full_messages
      redirect_to edit_encounter_path
    end
  end

  def destroy
    find_encounter_by_id # Sets encounter to @encounter
    if permitted?(@encounter.user)
      @encounter.destroy
      flash[:notice] = "Encounter Deleted."
      redirect_to my_encounters_path
    else
      flash[:notice] = "You are not authorized to delete that item."
      redirect_to encounters_path
    end
  end

  private

  def encounters_params
    params.require(:encounter).permit(:name, :content, monster_ids: [], character_ids: [])
  end

  def find_encounter_by_id
    @encounter = Encounter.find(params[:id])
  end

  def find_encounter_by_name
    @encounters = Encounter.where(Encounter.arel_table[:name].lower.matches(params[:search_term].downcase))
  end

  def set_monster_quantities(encounter)
    encounter.monster_encounters.each do |m_e|
      m_e.quantity = params[:encounter][:quantity]["#{m_e.monster.id}"]
      m_e.save
    end
  end

  def calculate_difficulty(encounter)
    monster_challenge_sum(encounter)
    player_level_avg(encounter)
    determine_challenge_rating(encounter)
  end

  def monster_challenge_sum(encounter)
    sum = 0.0
    monster_objs = Monster.where(id: encounter.monster_ids)

    monster_objs.each do |monster|
      sum += ( monster.challenge_rating * monster.quantity_by_encounter(encounter) )
    end

    sum
  end

  def player_level_avg(encounter)
    sum = 0.0
    char_objs = Character.where(id: encounter.character_ids)

    char_objs.each do |char|
      sum += char.level
    end

    average_player_level = (sum / char_objs.count)
    average_player_level
  end

  def determine_challenge_rating(encounter)
    difference = ( monster_challenge_sum(encounter) - player_level_avg(encounter) )

    case difference
    when 3...4
      encounter.difficulty = "Difficulty: Brutal"
    when 2...3
      encounter.difficulty = "Difficulty: Hard"
    when 1...2
      encounter.difficulty = "Difficulty: Challenging"
    when -1...-2
      encounter.difficulty = "Difficulty: Fairly Easy"
    when -2...-3
      encounter.difficulty = "Difficulty: Easy"
    when -3...-4
      encounter.difficulty = "Difficulty: Very Easy"
    else
      if difference >= 4
        encounter.difficulty = "Difficulty: Lethal"
      elsif difference <= -4
        encounter.difficulty = "Difficulty: Pushover"
      else
        encounter.difficulty = "Difficulty: Evenly Matched"
      end
    end
    encounter.save
  end

  def monsters_by_cr
    very_easy_monsters
    easy_monsters
    medium_monsters
    hard_monsters
    very_hard_monsters
    impossible_monsters
  end

  def very_easy_monsters
    @very_easy_monsters = Monster.where(challenge_rating: 0...1)
  end

  def easy_monsters
    @easy_monsters = Monster.where(challenge_rating: [1..3])
  end

  def medium_monsters
    @medium_monsters = Monster.where(challenge_rating: [4..7])
  end

  def hard_monsters
    @hard_monsters = Monster.where(challenge_rating: [8..10])
  end

  def very_hard_monsters
    @very_hard_monsters = Monster.where(challenge_rating: [11..20])
  end

  def impossible_monsters
    @impossible_monsters = Monster.where(challenge_rating: [21..30])
  end

end

app/helpers/encounters_helper.rb
module EncountersHelper
end

app/views/encounters/_encountersform.html.erb
<%= form_for @encounter, method: :get, url: url do |f| %>

  <%= f.label :name %>
    <br>
  <%= f.text_field :name %>
    <br><br>
  <%= f.label :content %>
    <br>
  <%= f.text_area :content, class: "encounter_description" %>
    <br></br>

  <% @encounter.monster_encounters.each do |m_e| %>
    <%= f.hidden_field :monster_quantity, {name: "encounter[quantity][#{m_e.monster.id}]", value: m_e.quantity} %>
  <% end %>

  <%= f.label "Very Easy Monsters", class: "very_easy_monster_type_titles"%>
  <div class="checkboxes_container">
  <%= f.collection_check_boxes :monster_ids, @very_easy_monsters, :id, :name do |b| %>
    <div class="checkboxes_inner_container">
      <%= b.check_box %>
      <%= b.label %>
    </div>
  <% end %>
  </div>

    <br><br>

  <%= f.label "Easy Monsters", class: "easy_monster_type_titles"%>
  <div class="checkboxes_container">
  <%= f.collection_check_boxes :monster_ids, @easy_monsters, :id, :name do |b| %>
    <div class="checkboxes_inner_container">
      <%= b.check_box %>
      <%= b.label %>
    </div>
  <% end %>
  </div>

    <br><br>

  <%= f.label "Medium Monsters", class: "medium_monster_type_titles"%>
  <div class="checkboxes_container">
  <%= f.collection_check_boxes :monster_ids, @medium_monsters, :id, :name do |b| %>
    <div class="checkboxes_inner_container">
      <%= b.check_box %>
      <%= b.label %>
    </div>
  <% end %>
  </div>
    <br>

  <%= f.label "Hard Monsters", class: "hard_monster_type_titles"%>
  <div class="checkboxes_container">
  <%= f.collection_check_boxes :monster_ids, @hard_monsters, :id, :name do |b| %>
    <div class="checkboxes_inner_container">
      <%= b.check_box %>
      <%= b.label %>
    </div>
  <% end %>
  </div>
    <br>

  <%= f.label "Very Hard Monsters", class: "very_hard_monster_type_titles"%>
  <div class="checkboxes_container">
  <%= f.collection_check_boxes :monster_ids, @very_hard_monsters, :id, :name do |b| %>
    <div class="checkboxes_inner_container">
      <%= b.check_box %>
      <%= b.label %>
    </div>
  <% end %>
  </div>
    <br>

  <%= f.label "Impossible Monsters", class: "impossible_monster_type_titles"%>
  <div class="checkboxes_container">
  <%= f.collection_check_boxes :monster_ids, @impossible_monsters, :id, :name do |b| %>
  <div class="checkboxes_inner_container">
    <%= b.check_box %>
    <%= b.label %>
  </div>
  <% end %>
  </div>
    <br>

  <%= f.label "Characters:" %>

  <%= f.collection_check_boxes :character_ids, @characters, :id, :char_name_and_level %>
    <br></br>

  <%= f.submit "Preview Encounter", :class => 'back_to_homepage_button' %>
<% end %>
  <br>

<%= button_to "Browse All Monsters", monsters_path, :method => :get, :class => 'back_to_homepage_button' %><br>
  <br>
<%= button_to "Browse All Characters", characters_path, :method => :get, :class => 'back_to_homepage_button' %><br>
  <br>
<%= button_to "Back to Homepage", root_path, :method => :get, :class => 'back_to_homepage_button' %><br>

app/views/encounters/_previewform.html.erb
<%= render 'partials/notices' %>
<h3>My Encounter:</h3>
<br>

<%= form_for @encounter, method: method do |f| %>

  <h4><%= @encounter.name %></h4>
  <%= f.hidden_field :name %>
  <ul>
    <li><%= @encounter.content %></li><br>
    <%= f.hidden_field :content %>
  </ul>

  <h5>Characters:</h5>
  <% @encounter.character_ids.each do |cid| %>
    <%= f.hidden_field :character_ids, {name: "encounter[character_ids][]", value: cid} %>
  <% end %>
  <ul>
    <% @encounter.characters.each do |character| %>
      <li><%= character.char_name_and_level %></li>
    <% end %>
  </ul><br>

  <h5>Monsters:</h5>
  <% @encounter.monster_ids.each do |mid| %>
    <%= f.hidden_field :monster_ids, {name: "encounter[monster_ids][]", value: mid} %>
  <% end %>

  <ul>
    <% @encounter.monster_encounters.each do |m_e| %>
      <li><%= m_e.monster.monster_name_and_cr %><br>
        <%= f.number_field :monster_quantity, {name: "encounter[quantity][#{m_e.monster.id}]", value: m_e.quantity} %></li>
    <% end %>
  </ul><br>

  <%= f.submit %>
<% end %>

app/views/encounters/_search.html.erb
<%= form_tag encounters_search_path, :method => :get do %>
  <%= label_tag(:search_term, "Search Encounters:") %>
  <%= text_field_tag :search_term %>
  <%= submit_tag 'Search Encounters' %>
<% end %>

app/views/encounters/edit.html.erb
<h1>Edit Encounter</h1>

<%= render "encountersform", url: edit_encounter_preview_path %>

app/views/encounters/edit_preview.html.erb
<%= render 'previewform', method: "patch" %>

app/views/encounters/index.html.erb
<h1>Current Encounters:</h1>
<%= render 'partials/encounters_index' %>

app/views/encounters/new.html.erb
<%= render "heading" %>

<%= render "/partials/errors" %>

<h1>Encounter Generator</h1>

<%= render "encountersform", url: encounter_preview_path %>

app/views/encounters/preview.html.erb
<%= render 'previewform', method: "post" %>

app/views/encounters/show.html.erb
<%= render 'partials/encounter_show' %>