config/routes.rb
Rails.application.routes.draw do
  # resources :character_encounters
  # resources :monster_encounters
  resources :char_class, only: [:index, :show]
  resources :char_race, only: [:index, :show]
  resources :alignment, only: [:index, :show]

  get "/pets/search", to: "pets#search", as: "pets_search"
  # resources :pets
  get "/characters/search", to: "characters#search", as: "characters_search"
  resources :characters
  get "/monsters/search", to: "monsters#search", as: "monsters_search"
  resources :monsters
  get "/encounters/search", to: "encounters#search", as: "encounters_search"
  get "/encounters/preview", to: "encounters#preview", as: "encounter_preview"
  get "/encounters/:id/edit/preview", to: "encounters#edit_preview", as: "edit_encounter_preview"
  resources :encounters


  get '/login', to: 'sessions#new', as: 'login'
  post '/sessions', to: 'sessions#create', as: 'sessions'
  post '/logout', to: 'sessions#destroy'

  resources :users, except: :index
  get '/signup', to: 'users#new', as: 'register'

  get '/users/:id/encounters', to: 'users#encounters_index', as: 'my_encounters'
  get '/users/:id/encounters/:encounter_id', to: 'users#encounter_show', as: 'my_encounter'

  get '/users/:id/characters', to: 'users#characters_index', as: 'my_characters'
  get '/users/:id/characters/:character_id', to: 'users#character_show', as: 'my_character'

  get '/users/:id/monsters', to: 'users#monsters_index', as: 'my_monsters'
  get '/users/:id/monsters/:monster_id', to: 'users#monster_show', as: 'my_monster'

  root 'application#home'
  get '/analytics', to: 'application#analytics'

  get "*path", to: 'application#redirect'
end

app/models/character.rb
class Character < ApplicationRecord
  has_many :character_encounters
  has_many :encounters, through: :character_encounter
  has_many :pets
  belongs_to :char_class
  belongs_to :char_race
  belongs_to :alignment
  belongs_to :user, optional: true

  validates :name, :strength, :dexterity, :constitution, :intelligence, :wisdom, :charisma, presence: true
  validates :strength, :dexterity, :constitution, :intelligence, :wisdom, :charisma, inclusion: { in: 0..20, message: "value must be between 0 and 20."}
  validates :name, uniqueness: true

  def char_name_and_level
    "#{name} (Level #{level}) "
  end
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  def index
    @characters = Character.all
  end

  def search
    find_character_by_name
    if @characters.length > 0
      render :index
    else
      flash[:errors] = "That character does not exist."
      redirect_to characters_path
    end
  end

  def new
    @character = Character.new
    @char_races = CharRace.all
    @char_classes = CharClass.all
    @alignments = Alignment.all
  end

  def show
    find_character_by_id #Assigns character to @character
    @char_races = CharRace.all
    @char_classes = CharClass.all
    @alignments = Alignment.all
  end

  def edit
    find_character_by_id #Assigns character to @character
    @char_races = CharRace.all
    @char_classes = CharClass.all
    @alignments = Alignment.all

    if !permitted?(@character.user)
      flash[:notice] = "You are not authorized to edit this item."
      redirect_to @character
    end
  end

  def create
    @character = Character.create(character_params)

    if @character.valid? && logged_in?
      @character.update(user_id: current_user.id)
      redirect_to my_character_path(current_user.id, @character)
    elsif @character.valid?
      redirect_to character_path(@character)
    else
      flash[:errors] = @character.errors.full_messages
      redirect_to new_character_path
    end

  end

  def update
    find_character_by_id #Assigns character to @character

    if @character.update(character_params)
      redirect_to @character
    else
      flash[:errors] = @character.errors.full_messages
      redirect_to edit_character_path
    end
  end

  def destroy
    find_character_by_id #Assigns character to @character
    if permitted?(@character.user)
      @character.destroy
      flash[:notice] = "Character Deleted."
      redirect_to my_characters_path
    else
      flash[:notice] = "You are not authorized to delete that item."
      redirect_to characters_path
    end
  end

  private

  def character_params
    params.require(:character).permit(:name, :char_class_id, :char_race_id, :alignment_id, :level, :experience, :strength, :dexterity, :constitution, :intelligence, :wisdom, :charisma)
  end

  def find_character_by_id
    @character = Character.find(params[:id])
  end

  def find_character_by_name
    @characters = Character.where(Character.arel_table[:name].lower.matches(params[:search_term].downcase))
  end
end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/views/characters/_characterform.html.erb
<%= form_for @character do |f| %>
<div class="character_background_new">
  <br><br><br><br>
  <img class="character_name" src = "/../assets/character_name_top.png">
    <br>
  <%= f.text_field :name, class: "character_name_new" %>
    <br>
  <img class= "character_name" src = "/../assets/character_name_bottom.png" >
    <br>
  <%= f.label "Character Class", class: "character_subtitles_new" %>
  <%= f.collection_select :char_class_id, @char_classes, :id, :name %>
  <br><br>
  <%= f.label "Character Race", class: "character_subtitles_new" %>
  <%= f.collection_select :char_race_id, @char_races, :id, :name %>
  <br><br>
  <%= f.label "Alignment", class: "character_subtitles_new" %>
  <%= f.collection_select :alignment_id, @alignments, :id, :name %>
  <br><br>
  <img class="character_dividers_new" src = "/../assets/red-divider.png"><br>
  <%= f.label :level, class: "character_subtitles_new" %><br>
  <%= f.number_field :level, class: "character_number_field" %>
  <br><br>
  <%= f.label :experience, class: "character_subtitles_new" %><br>
  <%= f.number_field :experience, class: "character_number_field" %>
  <br><br>
    <img class="character_dividers_new" src = "/../assets/red-divider.png"><br>
  <div class="character_input_container_new">
      <div class="character_input_inner_container">
  <%= f.label :strength, class: "character_form_size_new" %>
    <br>
  <%= f.number_field :strength, class: "character_main_stats_new" %>
      </div>
    <br><br><br>
      <div class="character_input_inner_container">
  <%= f.label :dexterity, class: "character_form_size_new" %>
    <br>
  <%= f.number_field :dexterity, class: "character_main_stats_new" %>
      </div>
    <br><br><br>
      <div class="character_input_inner_container">
  <%= f.label "Constitution", class: "character_form_size_new" %>
    <br>
  <%= f.number_field :constitution, class: "character_main_stats_new" %>
      </div>
    <br><br><br>
      <div class="character_input_inner_container">
  <%= f.label :intelligence, class: "character_form_size_new" %>
    <br>
  <%= f.number_field :intelligence, class: "character_main_stats_new" %>
      </div>
    <br><br><br>
      <div class="character_input_inner_container">
  <%= f.label :wisdom, class: "character_form_size_new" %>
    <br>
  <%= f.number_field :wisdom, class: "character_main_stats_new" %>
      </div>
    <br><br><br>
      <div class="character_input_inner_container">
  <%= f.label :charisma, class: "character_form_size_new" %>
    <br>
  <%= f.number_field :charisma, class: "character_main_stats_new" %>
      </div>
    <br><br>
  </div>
  <br>
  <img class="character_dividers_new" src = "/../assets/red-divider.png">
  <br><br><br>
  <%= f.submit class: "character_button_new" %>
  <br>
<% end %>
<br><br><br>
</div>

<%= button_to "<< Back to Homepage", root_path, :method => :get, :class => 'back_to_homepage_button' %><br>

app/views/characters/_search.html.erb
<%= form_tag characters_search_path, :method => :get do %>
  <%= label_tag(:search_term, "Search Characters:") %>
  <%= text_field_tag :search_term %>
  <%= submit_tag 'Search Characters' %>
<% end %>

app/views/characters/edit.html.erb
<%= render "heading" %>

<h1>Edit Character</h1>

<%= render "characterform" %>

app/views/characters/index.html.erb
<h1>Current Characters:</h1>
<%= flash[:notice] if flash[:notice] %>
<br>
<%= render "heading" %>
<br><br>
<br>
<%= render "search" %>
<p class="errors"><%= flash[:errors] if flash[:errors] %></p>
<ul>
  <% @characters.each do |character| %>
    <li><%= link_to character.name, character_path(character) %></li>
      <ul>
        <% character.pets.each do |pet| %>
          <li><u>Pets:</u> <%= link_to pet.name, pet_path(pet) %></li>
        <% end %>
      </ul>
  <% end %>
</ul>
<br></br>

<%= button_to "Create New Character", new_character_path, {method: :get} %><br>

<%= button_to "Back to Homepage", root_path, {method: :get} %>

app/views/characters/new.html.erb
<%= render "heading" %>

<%= render "/partials/errors" %>
<h1>Character Generator</h1>

<%= render "characterform" %>

app/views/characters/show.html.erb
<h1><%= @character.name %></h1>
<ul>
  <li>Class: <%= @character.char_class.name %></li>
  <li>Race: <%= @character.char_race.name %></li>
  <li>Alignment: <%= @character.alignment.name %></li>
  <br><br>
  <li>Level: <%= @character.level%></li>
  <li>Experience: <%= @character.experience%></li>
  <br><br>
  <li>Strength: <%= @character.strength %></li>
  <li>Dexterity: <%= @character.dexterity %></li>
  <li>Constitution: <%= @character.consitution %></li>
  <li>Intelligence: <%= @character.intelligence %></li>
  <li>Wisdom: <%= @character.wisdom %></li>
  <li>Charisma: <%= @character.charisma %></li>
</ul>
<p>Pets:</p>
<% @character.pets.each do |pet| %>
<ul>
  <li><%= pet.name %></li>
</ul>
<% end %>

<%= button_to "Edit", edit_character_path(@character), {method: :get} %><br>
<%= button_to "<< Return to All Characters", characters_path, {method: :get} %><br>

<%= form_tag @character, method: "DELETE" do %>
  <%= submit_tag "Delete this character", :onclick => "return confirm('Really delete this Character???')" %>
<% end %>