config/routes.rb
Rails.application.routes.draw do
  # resources :character_encounters
  # resources :monster_encounters
  resources :char_class, only: [:index, :show]
  resources :char_race, only: [:index, :show]
  resources :alignment, only: [:index, :show]

  get "/pets/search", to: "pets#search", as: "pets_search"
  # resources :pets
  get "/characters/search", to: "characters#search", as: "characters_search"
  resources :characters
  get "/monsters/search", to: "monsters#search", as: "monsters_search"
  resources :monsters
  get "/encounters/search", to: "encounters#search", as: "encounters_search"
  get "/encounters/preview", to: "encounters#preview", as: "encounter_preview"
  get "/encounters/:id/edit/preview", to: "encounters#edit_preview", as: "edit_encounter_preview"
  resources :encounters


  get '/login', to: 'sessions#new', as: 'login'
  post '/sessions', to: 'sessions#create', as: 'sessions'
  post '/logout', to: 'sessions#destroy'

  resources :users, except: :index
  get '/signup', to: 'users#new', as: 'register'

  get '/users/:id/encounters', to: 'users#encounters_index', as: 'my_encounters'
  get '/users/:id/encounters/:encounter_id', to: 'users#encounter_show', as: 'my_encounter'

  get '/users/:id/characters', to: 'users#characters_index', as: 'my_characters'
  get '/users/:id/characters/:character_id', to: 'users#character_show', as: 'my_character'

  get '/users/:id/monsters', to: 'users#monsters_index', as: 'my_monsters'
  get '/users/:id/monsters/:monster_id', to: 'users#monster_show', as: 'my_monster'

  root 'application#home'
  get '/analytics', to: 'application#analytics'

  get "*path", to: 'application#redirect'
end

app/models/alignment.rb
class Alignment < ApplicationRecord
  has_many :character
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/char_class.rb
class CharClass < ApplicationRecord
  has_many :character
end

app/models/char_race.rb
class CharRace < ApplicationRecord
  has_many :character
end

app/models/character.rb
class Character < ApplicationRecord
  has_many :character_encounters
  has_many :encounters, through: :character_encounter
  has_many :pets
  belongs_to :char_class
  belongs_to :char_race
  belongs_to :alignment
  belongs_to :user, optional: true

  validates :name, :strength, :dexterity, :constitution, :intelligence, :wisdom, :charisma, presence: true
  validates :strength, :dexterity, :constitution, :intelligence, :wisdom, :charisma, inclusion: { in: 0..20, message: "value must be between 0 and 20."}
  validates :name, uniqueness: true

  def char_name_and_level
    "#{name} (Level #{level}) "
  end
end

app/models/character_encounter.rb
class CharacterEncounter < ApplicationRecord
  belongs_to :encounter
  belongs_to :character
end

app/models/encounter.rb
class Encounter < ApplicationRecord
  has_many :character_encounters
  has_many :characters, through: :character_encounters
  has_many :monster_encounters
  has_many :monsters, through: :monster_encounters
  belongs_to :user, optional: true

  validates :name, :content, :characters, :monsters, presence: true
  validates :name, uniqueness: true

  def monster_quantity(num)
    monster_encounters.each do |m_e|
      m_e.quantity = num
    end
  end

  def encounter_difficulty=(string)
    @encounter_difficulty = string
  end

  def encounter_difficulty
    @encounter_difficulty
  end

end

app/models/monster.rb
class Monster < ApplicationRecord
  has_many :monster_encounters
  has_many :encounters, through: :monster_encounters
  belongs_to :user, optional: true

  # validates :name, :description, :hit_points, :size, :challenge_rating, :strength, :dexterity, :constitution, :intelligence, :wisdom, :charisma, :armor_class, presence: true
  validates :hit_points, inclusion: { in: 1..500, message: "value must be between 1 and 500."}

  def stats
    {strength: strength, dexterity: dexterity, constitution: constitution, intelligence: intelligence, wisdom: wisdom, charisma: charisma}
  end

  def quantity_by_encounter(encounter)
    encounter.monster_encounters.find_by(monster_id: self.id).quantity
  end

  def monster_name_and_cr
    "#{name} || CR #{challenge_rating}"
  end

  MONSTER_SIZES = ["Tiny", "Small", "Medium", "Large", "Huge", "Gargantuan"]

  end

app/models/monster_encounter.rb
class MonsterEncounter < ApplicationRecord
  belongs_to :encounter
  belongs_to :monster

  validates :quantity, numericality: {in: 0..10}
end

app/models/pet.rb
class Pet < ApplicationRecord
  belongs_to :character
  delegate :user_id, to: :character

  validates :name, :description, :character_id, presence: true
  validates :name, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :encounters
  has_many :characters
  has_many :monsters
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  def index
    @pets = Pet.all
  end

  def search
    find_pet_by_name
    if @pets.length > 0
      render :index
    else
      flash[:errors] = "That pet does not exist."
      redirect_to pets_path
    end
  end

  def new
    @pet = Pet.new
    @characters = Character.all
  end

  def create
    @pet = Pet.create(pet_params)
    if @pet.valid?
      redirect_to pet_path(@pet)
    else
      flash[:errors] = @pet.errors.full_messages
      redirect_to new_pet_path
    end
  end

  def show
    find_pet_by_id # Assigns pet to @pet
  end

  def edit
  end

  def update
    find_pet_by_id # Assigns pet to @pet
    if @pet.update(pet_params)
      redirect_to pet_path(@pet)
    else
      flash[:errors] = @pet.errors.full_messages
      redirect_to pet_path(@pet)
    end
  end

  def destroy
    find_pet_by_id # Assigns pet to @pet
    @pet.destroy
    flash[:notice] = "Pet Deleted."

    redirect_to pets_path
  end

  private

  def pet_params
    params.require(:pet).permit(:name, :description, :character_id)
  end

  def find_pet_by_id
    @pet = Pet.find(params[:id])
  end

  def find_pet_by_name
    @pets = Pet.where(Pet.arel_table[:name].lower.matches(params[:search_term].downcase))
  end
end

app/helpers/alignment_helper.rb
module AlignmentHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/char_class_helper.rb
module CharClassHelper
end

app/helpers/char_race_helper.rb
module CharRaceHelper
end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/helpers/encounters_helper.rb
module EncountersHelper
end

app/helpers/monsters_helper.rb
module MonstersHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/views/nav/_navbar.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Encounter Generator", '/', id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Encounters", encounters_path %></li>
        <li><%= link_to "Characters", characters_path %></li>
        <li><%= link_to "Monsters", monsters_path %></li>
        <% if logged_in? %>
          <li><%= link_to "Account", user_path(current_user) %></li>
          <li><%= link_to "Log out", logout_path, method: :post %></li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
          <li><%= link_to "Sign up", register_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/partials/_character_show.html.erb
<%= render 'partials/notices' %>
<div class="character_background">
<br>
<h1 class="character_show"><%= @character.name %></h1>
<% if @character.user %>
  <span class="character_subtitles"><b>Created by:</b><em><%= " #{@character.user.username.capitalize}" %></em></span></br>
<% end %>
  <span class="character_subtitles">Class:</span> <span class="character_info"><em><%= @character.char_class.name %></em></span></br>
  <span class="character_subtitles">Race:</span> <span class="character_info"><em><%= @character.char_race.name %></em></span></br>
  <span class="character_subtitles">Alignment:</span> <span class="character_info"><em><%= @character.alignment.name %></em></span></br>
  <img class="character_dividers" src = "/../assets/red-divider.png"><br>
  <span class="character_subtitles">Level:</span> <span class="character_info"><em><%= @character.level%></em></span></br>
  <span class="character_subtitles">Experience:</span> <span class="character_info"><em><%= @character.experience%></em></span></br>
  <img class="character_dividers" src = "/../assets/red-divider.png"><br>
  <span class="character_subtitles">Strength:</span> <span class="character_info"><em><%= @character.strength %></em></span></br>
  <span class="character_subtitles">Dexterity:</span> <span class="character_info"><em><%= @character.dexterity %></em></span></br>
  <span class="character_subtitles">Constitution:</span> <span class="character_info"><em><%= @character.constitution %></em></span></br>
  <span class="character_subtitles">Intelligence:</span> <span class="character_info"><em><%= @character.intelligence %></em></span></br>
  <span class="character_subtitles">Wisdom:</span> <span class="character_info"><em><%= @character.wisdom %></em></span></br>
  <span class="character_subtitles">Charisma:</span> <span class="character_info"><em><%= @character.charisma %></em></span></br>
  <% if @character.pets.count > 0 %>
  <h3 class="character_show">Pets:</h3>
  <% end %>
<% @character.pets.each do |pet| %>
  <span class="character_subtitles">Pet Name:</span> <span class="character_info"><%= pet.name %></span>
<% end %>
<br><br>
</div>
<br>

<% if permitted?(@character.user) %>
  <%= button_to "Edit", edit_character_path(@character), :method => :get, :class => 'back_to_homepage_button' %>
<% end %><br>

<% if logged_in? %>
  <%= button_to "<< Return to My Characters", my_characters_path, :method => :get, :class => 'back_to_homepage_button' %><br>
<% end %>
<%= button_to "<< Return to All Characters", characters_path, :method => :get, :class => 'back_to_homepage_button'  %><br>

<%= button_to "Delete This Character", @character, {method: :delete, :onclick => "return confirm('Really delete this character?')", :class => 'delete_button'} %><br>

app/views/partials/_characters_index.html.erb
<%= render 'partials/notices' %>
<br>
<%= render "characters/heading" %>
<br><br>
<br>
<%= render "characters/search" %>

<p class="errors"><%= flash[:errors] if flash[:errors] %></p>

<ul>
  <% @characters.each do |character| %>

    <% if character.user == current_user && logged_in? %>
      <li><%= link_to character.name, my_character_path(character.user_id, character) %></li><br>
    <% else %>
      <li><%= link_to character.name, character_path(character) %></li><br>
    <% end %>
      <ul>
        <% character.pets.each do |pet| %>
          <li><u>Pets:</u> <%= link_to pet.name, pet_path(pet) %></li>
        <% end %>
      </ul>
  <% end %>
</ul>
<br></br>

<%= button_to "Create New Character", new_character_path, :method => :get, :class => 'create_new_button' %><br>

<%= button_to "<< Back to Homepage", root_path, :method => :get, :class => 'back_to_homepage_button' %>

app/views/partials/_encounter_show.html.erb
<%= render 'partials/notices' %>

<h1 class="encounter_show"><%= @encounter.name %></h1>
<% if @encounter.user %>
  <p><b>Created by:</b><%= " #{@encounter.user.username.capitalize}" %></p>
<% end %>
<p><b>Description:</b> <em><%= @encounter.content %></em></p>

<h2><%= @encounter.difficulty %></h2>

  <% if @encounter.characters.count % 2 == 0 %>
    <div class="two_encounter_columns">
  <% elsif @encounter.characters.count % 3 == 0 %>
    <div class="three_encounter_columns">
  <% elsif @encounter.characters.count == 1 %>
    <div class="one_encounter_columns">
  <% end %>

  <% @encounter.characters.each do |character| %>
    <% if @encounter.characters.count % 3 == 0 %>
    <div class="three_character_background">
    <% else %>
    <div class="character_background">
    <% end %>
    <br>
    <h3 class="character_show"><%= character.name %></h3>
    <span class="character_subtitles">Class:</span> <span class="character_info"><em><%= character.char_class.name %></em></span></br>
    <span class="character_subtitles">Race:</span> <span class="character_info"><em><%= character.char_race.name %></em></span></br>
    <span class="character_subtitles">Alignment:</span> <span class="character_info"><em><%= character.alignment.name %></em></span></br>
      <% if @encounter.characters.count % 3 == 0 %>
      <img class="three_character_dividers" src = "/../assets/red-divider.png"><br>
      <% else %>
      <img class="character_dividers" src = "/../assets/red-divider.png"><br>
      <% end %>
    <span class="character_subtitles">Level:</span> <span class="character_info"><em><%= character.level%></em></span></br>
    <span class="character_subtitles">Experience:</span> <span class="character_info"><em><%= character.experience%></em></span></br>
      <% if @encounter.characters.count % 3 == 0 %>
      <img class="three_character_dividers" src = "/../assets/red-divider.png"><br>
      <% else %>
      <img class="character_dividers" src = "/../assets/red-divider.png"><br>
      <% end %>
    <span class="character_subtitles">Strength:</span> <span class="character_info"><em><%= character.strength %></em></span></br>
    <span class="character_subtitles">Dexterity:</span> <span class="character_info"><em><%= character.dexterity %></em></span></br>
    <span class="character_subtitles">Constitution:</span> <span class="character_info"><em><%= character.constitution %></em></span></br>
    <span class="character_subtitles">Intelligence:</span> <span class="character_info"><em><%= character.intelligence %></em></span></br>
    <span class="character_subtitles">Wisdom:</span> <span class="character_info"><em><%= character.wisdom %></em></span></br>
    <span class="character_subtitles">Charisma:</span> <span class="character_info"><em><%= character.charisma %></em></span></br>
    <br><br>
    </div>
  <% end %>
  </div>

<h3 class="versus"><center>vs.</center></h3>

  <% if @encounter.monster_encounters.count % 2 == 0 %>
    <div class="two_encounter_columns">
  <% elsif @encounter.monster_encounters.count % 3 == 0 %>
    <div class="three_encounter_columns">
  <% elsif @encounter.monster_encounters.count == 1 %>
    <div class="one_encounter_columns">
  <% end %>

  <% @encounter.monster_encounters.each do |m_e| %>
    <% if @encounter.monster_encounters.count % 3 == 0 %>
      <div class="three_encounter_container">
    <% else %>
      <div class="encounter_container">
    <% end %>
    <% if @encounter.monster_encounters.count % 3 == 0 %>
    <div class="three_monster_background">
    <% else %>
    <div class="monster_background">
    <% end %>
    <br><br>
    <h3 class="character_show"><%= m_e.monster.name %> <b>(<%= m_e.quantity %>)</b></h3>
    <span class="monster_subtitles"><b>Description:</b></span> <span class="monster_info"><em><%= m_e.monster.description %></em></span></br>
    <% if @encounter.characters.count % 3 == 0 %>
    <img class="three_monster_dividers" src = "/../assets/red-divider.png"><br>
    <% else %>
    <img class="monster_dividers" src = "/../assets/red-divider.png"><br>
    <% end %>
    <span class="monster_subtitles"><b>Size:</b></span> <span class="monster_info"><%= m_e.monster.size %></span></br>
    <span class="monster_subtitles"><b>Challenge Rating:</b></span> <span class="monster_info"><%= m_e.monster.challenge_rating %></span></br>
    <span class="monster_subtitles"><b>Armor Class:</b></span> <span class="monster_info"><%= m_e.monster.armor_class %></span></br>
    <span class="monster_subtitles"><b>Hit Points:</b></span> <span class="monster_info"><%= m_e.monster.hit_points %></span></br>
    <% if @encounter.monster_encounters.count % 3 == 0 %>
    <img class="three_monster_dividers" src = "/../assets/red-divider.png"><br>
    <% else %>
    <img class="monster_dividers" src = "/../assets/red-divider.png"><br>
    <% end %>
    <span class="monster_subtitles"><b>Strength:</b></span> <span class="monster_info"><em><%= m_e.monster.strength %></em></span></br>
    <span class="monster_subtitles"><b>Dexterity:</b></span> <span class="monster_info"><em><%= m_e.monster.dexterity %></em></span></br>
    <span class="monster_subtitles"><b>Constitution:</b></span> <span class="monster_info"><em><%= m_e.monster.constitution %></em></span></br>
    <span class="monster_subtitles"><b>Intelligence:</b></span> <span class="monster_info"><em><%= m_e.monster.intelligence %></em></span></br>
    <span class="monster_subtitles"><b>Wisdom:</b></span> <span class="monster_info"><em><%= m_e.monster.wisdom %></em></span></br>
    <span class="monster_subtitles"><b>Charisma:</b></span> <span class="monster_info"><em><%= m_e.monster.charisma %></em></span></br>
    <span class="monster_subtitles"><b>Constituion Saving Throw:</b></span> <span class="monster_info"><em><%= m_e.monster.constitution_save %></em></span></br>
    <span class="monster_subtitles"><b>Intelligence Saving Throw:</b></span> <span class="monster_info"><em><%= m_e.monster.intelligence_save %></em></span></br>
    <span class="monster_subtitles"><b>Wisdom Saving Throw:</b></span> <span class="monster_info"><em><%= m_e.monster.wisdom_save %></em></span></br>
    <span class="monster_subtitles"><b>History:</b></span> <span class="monster_info"><em><%= m_e.monster.history %></em></span></br>
    <span class="monster_subtitles"><b>Perception:</b></span> <span class="monster_info"><em><%= m_e.monster.perception %></em></span></br>
    <br><br>
    </div>
  </div>
  <% end %>
  </div>

<% if permitted?(@encounter.user) %>
  <%= button_to "Edit", edit_encounter_path(@encounter), {method: :get} %>
<% end %><br>

<% if logged_in? %>
  <%= button_to "<< Return to My Encounters", my_encounters_path, :method => :get, :class => 'back_to_homepage_button' %><br>
<% end %>
<%= button_to "<< Return to All Encounters", encounters_path, :method => :get, :class => 'back_to_homepage_button' %><br>

<%= button_to "Delete This Encounter", @encounter, {method: :delete, :onclick => "return confirm('Really delete this encounter?')", :class => 'delete_button'} %><br>

app/views/partials/_encounters_index.html.erb
<%= render 'partials/notices' %>
<br>
<%= render "encounters/heading" %>
<br>
<br>
<br>
<%= render "encounters/search" %>
<p class="errors"><%= flash[:errors] if flash[:errors] %></p>

<ul>
  <% @encounters.each do |encounter| %>
    <% if encounter.user == current_user && logged_in? %>
      <li><%= link_to encounter.name, my_encounter_path(encounter.user_id, encounter) %></li><br>
    <% else %>
      <li><%= link_to encounter.name, encounter_path(encounter) %></li><br>
    <% end %>
  <% end %>
</ul>
<br><br>

<%= button_to "Create New Encounter", new_encounter_path, :method => :get, :class => 'create_new_button' %><br>
  <br>
<%= button_to "<< Back to Homepage", root_path, :method => :get, :class => 'back_to_homepage_button' %>

app/views/partials/_errors.html.erb
<% if flash[:errors] %>
  <h3>You have errors:</h3>
  <ul>
    <% flash[:errors].each do |error| %>
      <li><%= error %></li>
    <% end %>
  </ul>
<% end %>

app/views/partials/_monster_show.html.erb
<%= render 'partials/notices' %>
<div class="monster_background">
<br><br>
<h1 class="monster_show"><%= @monster.name %></h1>
<span class="monster_subtitles"><b>Description:</b></span> <span class="monster_info"><em><%= @monster.description %></em></span></br>
<% if @monster.user %>
  <span class="monster_subtitles"><b>Created by:</b><em><%= " #{@monster.user.username.capitalize}" %></em></span></br>
<% end %>
<img class="monster_dividers" src = "/../assets/red-divider.png"><br>
<span class="monster_subtitles"><b>Size:</b></span> <span class="monster_info"><%= @monster.size %></span></br>
<span class="monster_subtitles"><b>Challenge Rating:</b></span> <span class="monster_info"><%= @monster.challenge_rating %></span></br>
<span class="monster_subtitles"><b>Armor Class:</b></span> <span class="monster_info"><%= @monster.armor_class %></span></br>
<span class="monster_subtitles"><b>Hit Points:</b></span> <span class="monster_info"><%= @monster.hit_points %></span></br>
<img class="monster_dividers" src = "/../assets/red-divider.png"><br>
  <span class="monster_subtitles"><b>Strength:</b></span> <span class="monster_info"><em><%= @monster.strength %></em></span></br>
  <span class="monster_subtitles"><b>Dexterity:</b></span> <span class="monster_info"><em><%= @monster.dexterity %></em></span></br>
  <span class="monster_subtitles"><b>Constitution:</b></span> <span class="monster_info"><em><%= @monster.constitution %></em></span></br>
  <span class="monster_subtitles"><b>Intelligence:</b></span> <span class="monster_info"><em><%= @monster.intelligence %></em></span></br>
  <span class="monster_subtitles"><b>Wisdom:</b></span> <span class="monster_info"><em><%= @monster.wisdom %></em></span></br>
  <span class="monster_subtitles"><b>Charisma:</b></span> <span class="monster_info"><em><%= @monster.charisma %></em></span></br>
  <span class="monster_subtitles"><b>Constituion Saving Throw:</b></span> <span class="monster_info"><em><%= @monster.constitution_save %></em></span></br>
  <span class="monster_subtitles"><b>Intelligence Saving Throw:</b></span> <span class="monster_info"><em><%= @monster.intelligence_save %></em></span></br>
  <span class="monster_subtitles"><b>Wisdom Saving Throw:</b></span> <span class="monster_info"><em><%= @monster.wisdom_save %></em></span></br>
  <span class="monster_subtitles"><b>History:</b></span> <span class="monster_info"><em><%= @monster.history %></em></span></br>
  <span class="monster_subtitles"><b>Perception:</b></span> <span class="monster_info"><em><%= @monster.perception %></em></span></br>
<br><br>
</div>
<br>

<% if permitted?(@monster.user) %>
  <%= button_to "Edit Monster", edit_monster_path(@monster), :method => :get, :class => "create_new_button" %>
<% end %><br>

<%= button_to "Delete This Monster", @monster, {method: :delete, :class => "delete_button", :onclick => "return confirm('Really delete this monster?')"} %><br>
<br>

<% if logged_in? %>
  <%= button_to "<< Return to My Monsters", my_monsters_path, :method => :get, :class => 'back_to_homepage_button' %><br>
<% end %>
<%= button_to "<< Return to All Monsters", monsters_path, :method => :get, :class => 'back_to_homepage_button' %><br>

app/views/partials/_monsters_index.html.erb
<%= render 'partials/notices' %>
<br>
<%= render "monsters/heading" %>
<br>
<br>
<br>
<%= render "monsters/search" %>
<p class="errors"><%= flash[:errors] if flash[:errors] %></p>

<br>

<div class="checkboxes_container">
  <% @monsters.each do |monster| %>
    <div class="checkboxes_inner_container">
      <% if permitted?(monster.user) %>
        <div class="monster"><%= link_to monster.name, my_monster_path(monster.user_id, monster) %><%= " [HB] (#{monster.description})" %></div><br>
      <% else %>
        <div class= "monster"><%= link_to monster.name, monster_path(monster) %><%= " (#{monster.description})" %></div>
      <% end %>
    </div>
  <% end %>
</div>
<br><br>

<%= button_to "Create New Monster", new_monster_path, :method => :get, :class => 'create_new_button' %><br>
<%= button_to "<< Back to Homepage", root_path, :method => :get, :class => 'back_to_homepage_button' %>

app/views/partials/_notices.html.erb
<%= flash[:notice] if flash[:notice] %>